name = "discord-calendar-bot"
main = "src/index.ts"
compatibility_date = "2022-12-07"

[triggers]
crons = [ "0 5 * * *" ]

[vars]
DISCORD_GUILD_ID = "1023106216328712282"
DISCORD_ANNOUNCEMENTS_CHANNEL_ID = "1046916574021419058"