name = "discord-calendar-bot"
main = "src/index.ts"
compatibility_date = "2022-12-07"

[triggers]
crons = [ "0 21 * * *" ]

[vars]
DISCORD_API_TOKEN = ""
DISCORD_GUILD_ID = "1023106216328712282"
DISCORD_ANNOUNCEMENTS_CHANNEL_ID = "1023108581526077550"